version: "3"
services:
  site:
    container_name: site
    build:
      context: site/
      dockerfile: Dockerfile
    ports:
      - 8080:80
  site2:
    container_name: site2
    build:
      context: site/
      dockerfile: Dockerfile
    ports:
      - 8081:80
  nginx:
    build:
      context: nginx/
    ports:
      - 8000:80
    depends_on:
      - site
      - site2
  database:
    image: mariadb:10.2
    environment:
      MYSQL_USER: MoraGames
      MYSQL_PASSWORD: MoraGames
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - 8001:80
    volumes:
      - ./database:/var/lib/mysql
    
volumes:
  database: